import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import 'react-toastify/dist/ReactToastify.css';
import '@mantine/tiptap/styles.css';

import { ColorSchemeScript, MantineProvider } from "@mantine/core";

import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/lib/providers/providet";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
      <ToastContainer />
        <Providers>
        <MantineProvider
          theme={{
            headings: { fontFamily: "Poppins, sans-serif" },
          }}
        >
            {children}
        </MantineProvider>
            </Providers>
      </body>
    </html>
  );
}
