const config = {
   API_URL: process.env.NEXT_PUBLIC_API_URL,
   FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
   FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
   FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
   MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
   FIREBASE_APP_ID: process.env.NEXT_PUBLIC_APP_ID,
   MEASUREMENT_ID: process.env.NEXT_PUBLIC_MEASUREMENT_ID,
   VAPID_KEY: process.env.NEXT_PUBLIC_VAPID_KEY,
   FCM_API_KEY: process.env.NEXT_PUBLIC_FCM_API_KEY
}

export default config